import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import Chart from '../CdcChartComponent'
import {
  assertVisualizationRendered,
  waitForEditor,
  openAccordion,
  MIN_ANIMATION_DELAY_MS
} from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof Chart> = {
  title: 'Components/Templates/Chart/Accessible Alt Text',
  component: Chart,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates SVG title/desc accessibility: auto-generated, static override, and metadata-driven modes for both title and description.'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof Chart>

const expectedMetadataDesc = altTextConfig.dataMetadata.altDescription

export const MetadataDriven: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'metadata', metadataKey: 'altTitle' },
        description: { type: 'metadata', metadataKey: 'altDescription' }
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Both title and description pulled from dataMetadata. The SVG contains <title> and <desc> elements referenced via aria-labelledby.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe(altTextConfig.dataMetadata.altTitle)

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe(expectedMetadataDesc)

    expect(svg?.getAttribute('aria-labelledby')).toContain(titleEl?.id)
    expect(svg?.getAttribute('aria-labelledby')).toContain(descEl?.id)
  }
}

export const StaticOverride: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'static', value: 'COVID positivity trend' },
        description: {
          type: 'static',
          value: 'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
        }
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story: 'Both title and description are static manually written strings.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('COVID positivity trend')

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe(
      'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
    )
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured. Falls back to the auto-generated SVG title element: "Line chart with the title: COVID-19 Test Positivity". No desc element is rendered.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('Line chart with the title: COVID-19 Test Positivity')

    const descEl = svg?.querySelector('desc')
    expect(descEl).toBeFalsy()
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'metadata', metadataKey: 'altTitle' },
        description: { type: 'metadata', metadataKey: 'altDescription' }
      }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story:
          'Editor mode showing the alt text controls in the General accordion with both title and description configured from metadata.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    await openAccordion(canvas, 'General')

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    const previewText = canvasElement.querySelector('[data-testid="alt-text-preview"]')
    expect(previewText).toBeTruthy()
    expect(previewText?.textContent).toContain('COVID-19 test positivity')

    const descPreview = canvasElement.querySelector('[data-testid="alt-text-desc-preview"]')
    expect(descPreview).toBeTruthy()
    expect(descPreview?.textContent).toContain('COVID-19 test positivity')
  }
}
