import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import Chart from '../CdcChartComponent'
import {
  assertVisualizationRendered,
  waitForEditor,
  openAccordion,
  MIN_ANIMATION_DELAY_MS
} from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof Chart> = {
  title: 'Components/Templates/Chart/Accessible Alt Text',
  component: Chart,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates the three alt text modes: auto-generated (default), static (manual override), and metadata-driven (pulled from data file metadata).'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof Chart>

const expectedMetadataAlt = altTextConfig.dataMetadata.altDescription

export const MetadataDriven: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Alt text type set to "metadata" with key "altDescription". The SVG aria-label is populated from dataMetadata.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe(expectedMetadataAlt)
  }
}

export const StaticOverride: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        type: 'static',
        value: 'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Alt text type set to "static" with a manually written description. The SVG aria-label uses the static value directly.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe(
      'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
    )
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured (type is "none"). Falls back to the auto-generated aria-label: "Line chart with the title: COVID-19 Test Positivity".'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe('Line chart with the title: COVID-19 Test Positivity')
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story:
          'Editor mode showing the "Accessible Alt Text" accordion with the type dropdown set to "Data File Metadata" and the metadata key selector.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    await openAccordion(canvas, 'Accessible Alt Text')

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    const previewText = canvasElement.querySelector('[data-testid="alt-text-preview"]')
    expect(previewText).toBeTruthy()
    expect(previewText?.textContent).toContain('COVID-19 test positivity')
  }
}
