import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import Chart from '../CdcChartComponent'
import {
  assertVisualizationRendered,
  waitForPresence,
  waitForEditor,
  openAccordion,
  MIN_ANIMATION_DELAY_MS
} from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof Chart> = {
  title: 'Components/Templates/Chart/Accessible Alt Text',
  component: Chart,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates SVG title/desc accessibility: auto-generated title with optional configurable description via static text or data file metadata.'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof Chart>

export const MetadataDescription: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Description pulled from dataMetadata while the title remains auto-generated. The SVG contains <title> and <desc> elements referenced via aria-labelledby.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('Line chart with the title: COVID-19 Test Positivity')

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe(altTextConfig.dataMetadata.altDescription)

    expect(svg?.getAttribute('aria-labelledby')).toContain(titleEl?.id)
    expect(svg?.getAttribute('aria-labelledby')).toContain(descEl?.id)
  }
}

export const StaticDescription: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        type: 'static',
        value: 'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story: 'Static manually written description with the auto-generated title.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('Line chart with the title: COVID-19 Test Positivity')

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe(
      'COVID-19 positivity has doubled in 8 weeks, suggesting increased community transmission.'
    )
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured. Falls back to the auto-generated SVG title element: "Line chart with the title: COVID-19 Test Positivity". No desc element is rendered.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('Line chart with the title: COVID-19 Test Positivity')

    const descEl = svg?.querySelector('desc')
    expect(descEl).toBeFalsy()
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story:
          'Editor mode showing the alt text description control in the General accordion with metadata-driven description.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    await openAccordion(canvas, 'General')

    if (MIN_ANIMATION_DELAY_MS > 0) {
      await new Promise(resolve => setTimeout(resolve, MIN_ANIMATION_DELAY_MS))
    }

    const descPreview = await waitForPresence('[data-testid="alt-text-desc-preview"]', canvasElement)
    expect(descPreview?.textContent).toContain('COVID-19 test positivity')
  }
}
