import { C as D } from "./storybook-CdcChart-ff690310.es.js";
import "./storybook-index-45401197.es.js";
import "./storybook-_commonjsHelpers-c5d32002.es.js";
import "./storybook-isSolr-cb863e7a.es.js";
import "./storybook-Filters-085415ef.es.js";
import "./storybook-index-633d712d.es.js";
import "./storybook-extends-70f3d2a3.es.js";
import "./storybook-Icon-96a1fdd8.es.js";
import "./storybook-index-43433e35.es.js";
import "./storybook-jsx-runtime-36872362.es.js";
import "./storybook-lodash-c15d8e1c.es.js";
import "./storybook-Button-d74e310e.es.js";
import "./storybook-MultiSelect-1c07e577.es.js";
import "./storybook-Tooltip-edc0f7ab.es.js";
import "./storybook-NestedDropdown-116432d3.es.js";
import "./storybook-coveUpdateWorker-cf57c593.es.js";
import "./storybook-debounce-cc216a80.es.js";
import "./storybook-memoize-b2d53f3a.es.js";
import "./storybook-isSymbol-227578c5.es.js";
import "./storybook-papaparse.min-b07ddc33.es.js";
import "./storybook-index-e5bf02db.es.js";
import "./storybook-InputToggle-1c80137d.es.js";
import "./storybook-chroma-b564050a.es.js";
import "./storybook-Group-e6c0d0df.es.js";
import "./storybook-string-7df1b381.es.js";
import "./storybook-index-4ed993c7.es.js";
import "./storybook-DataTable-d3306182.es.js";
import "./storybook-Loading-f180d060.es.js";
import "./storybook-year-24bd1dc7.es.js";
import "./storybook-numberFromString-24623c03.es.js";
import "./storybook-Table-12c53202.es.js";
import "./storybook-Circle-4d1a558c.es.js";
import "./storybook-DataTransform-1390427f.es.js";
import "./storybook-footnoteSymbols-c8ec8308.es.js";
import "./storybook-DataTableEditor-5aedf4d7.es.js";
import "./storybook-useDebounce-78f40efd.es.js";
import "./storybook-InputSelect-20478396.es.js";
import "./storybook-icon-check-0ef17e76.es.js";
import "./storybook-Accordion-0408a951.es.js";
import "./storybook-index-e502eacf.es.js";
import "./storybook-useDataVizClasses-707a8d8e.es.js";
import "./storybook-cacheBustingString-7a3dd9ba.es.js";
const C = "chart", I = !1, m = {
  noData: "No Data Available"
}, T = "Combo Bar-Line Chart", v = !0, R = !1, A = "theme-purple", G = !1, V = "medium", b = "hover", F = "Same as Line", E = "false", w = !1, O = "circle", H = "two-tone", P = "regular", M = "", x = "standard", Q = "top", U = !1, k = {
  showDownloadButton: !1
}, Y = {
  left: 5,
  right: 5
}, z = [
  {
    type: "suppression",
    seriesKey: "",
    label: "Suppressed",
    column: "Data 2",
    value: "ABC",
    style: "",
    displayTooltip: !0,
    displayLegend: !0,
    displayTable: !0,
    symbol: "Dagger",
    iconCode: "†",
    lineCode: ""
  }
], B = {
  hideAxis: !1,
  displayNumbersOnBar: !1,
  hideLabel: !1,
  hideTicks: !1,
  size: "68",
  gridLines: !0,
  enablePadding: !1,
  min: "",
  max: "",
  labelColor: "#333",
  tickLabelColor: "#333",
  tickColor: "#333",
  rightHideAxis: !0,
  rightAxisSize: 50,
  rightLabel: "",
  rightLabelOffsetSize: 0,
  rightAxisLabelColor: "#333",
  rightAxisTickLabelColor: "#333",
  rightAxisTickColor: "#333",
  numTicks: "",
  axisPadding: 0,
  scalePadding: 10,
  tickRotation: 0,
  anchors: [],
  label: "Y-Axis Label Example"
}, $ = {
  plots: [],
  borders: "true",
  firstQuartilePercentage: 25,
  thirdQuartilePercentage: 75,
  boxWidthPercentage: 40,
  plotOutlierValues: !1,
  plotNonOutlierValues: !0,
  legend: {
    showHowToReadText: !1,
    howToReadText: ""
  },
  labels: {
    q1: "Lower Quartile",
    q2: "q2",
    q3: "Upper Quartile",
    q4: "q4",
    minimum: "Minimum",
    maximum: "Maximum",
    mean: "Mean",
    median: "Median",
    sd: "Standard Deviation",
    iqr: "Interquartile Range",
    total: "Total",
    outliers: "Outliers",
    values: "Values"
  }
}, N = {
  hasLine: !1
}, W = !1, j = 0.35, K = 25, q = 15, X = {
  vertical: 300,
  horizontal: 750
}, J = {
  sortDates: !1,
  anchors: [],
  type: "date",
  showTargetLabel: !0,
  targetLabel: "Target",
  hideAxis: !1,
  hideLabel: !1,
  hideTicks: !1,
  size: "78",
  tickRotation: "25",
  min: "",
  max: "",
  labelColor: "#333",
  tickLabelColor: "#333",
  tickColor: "#333",
  numTicks: "",
  labelOffset: 65,
  axisPadding: 0,
  target: 0,
  maxTickRotation: 0,
  showSuppressedSymbol: !0,
  showSuppressedLine: !0,
  dataKey: "Date",
  label: "X-Axis Example Label",
  dateParseFormat: "%d/%m/%Y",
  dateDisplayFormat: "%d/%m/%Y",
  tickWidthMax: 91,
  padding: 6
}, Z = {
  label: "Data Table",
  expanded: !0,
  limitHeight: !1,
  height: "",
  caption: "",
  showDownloadUrl: !1,
  showDataTableLink: !0,
  indexLabel: "",
  download: !0,
  showVertical: !1,
  dateDisplayFormat: "",
  show: !0
}, tt = "vertical", at = "pinkpurple", et = {}, ot = {
  hide: !1,
  behavior: "highlight",
  axisAlign: !0,
  singleRow: !1,
  colorCode: "",
  reverseLabelOrder: !1,
  description: "",
  dynamicLegend: !1,
  dynamicLegendDefaultText: "Show All",
  dynamicLegendItemLimit: 5,
  dynamicLegendItemLimitMessage: "Dynamic Legend Item Limit Hit.",
  dynamicLegendChartMessage: "Select Options from the Legend",
  lineMode: !1,
  verticalSorted: !1,
  highlightOnHover: !1,
  hideSuppressedLabels: !1,
  seriesHighlight: [],
  position: "right",
  label: "Data Type"
}, it = {
  height: 25,
  active: !1,
  data: [
    {
      Date: "1/15/2016",
      "Data 1": "1000",
      "Data 2": "110",
      "Data 3": "100",
      "Data 4": "90",
      "Monthly-Goal": "100"
    },
    {
      Date: "2/15/2016",
      "Data 1": "100",
      "Data 2": "110",
      "Data 3": "100",
      "Data 4": "100",
      "Monthly-Goal": "100"
    },
    {
      Date: "3/15/2016",
      "Data 1": "80",
      "Data 2": "90",
      "Data 3": "100",
      "Data 4": "120",
      "Monthly-Goal": "110"
    },
    {
      Date: "4/15/2016",
      "Data 1": "80",
      "Data 2": "90",
      "Data 3": "110",
      "Data 4": "120",
      "Monthly-Goal": "110"
    },
    {
      Date: "5/15/2016",
      "Data 1": "70",
      "Data 2": "90",
      "Data 3": "110",
      "Data 4": "130",
      "Monthly-Goal": "120"
    },
    {
      Date: "6/15/2016",
      "Data 1": "100",
      "Data 2": "120",
      "Data 3": "120",
      "Data 4": "130",
      "Monthly-Goal": "120"
    },
    {
      Date: "7/15/2016",
      "Data 1": "110",
      "Data 2": "140",
      "Data 3": "120",
      "Data 4": "130",
      "Monthly-Goal": "130"
    },
    {
      Date: "8/15/2016",
      "Data 1": "110",
      "Data 2": "130",
      "Data 3": "120",
      "Data 4": "140",
      "Monthly-Goal": "130"
    },
    {
      Date: "9/15/2016",
      "Data 1": "120",
      "Data 2": "130",
      "Data 3": "120",
      "Data 4": "150",
      "Monthly-Goal": "140"
    }
  ]
}, rt = {
  active: !1,
  keys: []
}, nt = "qualitative-soft", ct = !1, lt = {
  palette: "monochrome-1",
  isPaletteReversed: !1
}, st = !0, dt = {
  commas: !1,
  prefix: "",
  suffix: "",
  abbreviated: !1,
  bottomSuffix: "",
  bottomPrefix: "",
  bottomAbbreviated: !1
}, St = {}, gt = {
  border: !0,
  accent: !0,
  background: !0,
  verticalHoverLine: !1,
  horizontalHoverLine: !1
}, ft = !1, Lt = "Filter Change", _t = [], ut = [
  {
    dataKey: "Data 2",
    type: "Bar",
    axis: "Left",
    tooltip: !0
  }
], pt = {
  opacity: 90,
  singleSeries: !1,
  dateDisplayFormat: ""
}, yt = {
  startAt: 0,
  colors: {
    line: "",
    shape: ""
  },
  lineOfNoEffect: {
    show: !0
  },
  type: "",
  pooledResult: {
    diamondHeight: 5,
    column: ""
  },
  estimateField: "",
  estimateRadius: "",
  shape: "",
  rowHeight: 20,
  description: {
    show: !0,
    text: "description",
    location: 0
  },
  result: {
    show: !0,
    text: "result",
    location: 100
  },
  radius: {
    min: 1,
    max: 8,
    scalingColumn: ""
  },
  regression: {
    lower: 0,
    upper: 0,
    estimateField: 0
  },
  leftWidthOffset: 0,
  rightWidthOffset: 0,
  showZeroLine: !1,
  leftLabel: "",
  rightLabel: "",
  hideDateCategoryCol: !1
}, ht = {
  isStacked: !1
}, Dt = {
  title: {
    defaultColor: "black"
  },
  iterations: 1,
  rxValue: 0.9,
  overallSize: {
    width: 900,
    height: 700
  },
  margin: {
    margin_y: 25,
    margin_x: 0
  },
  nodeSize: {
    nodeWidth: 26,
    nodeHeight: 40
  },
  nodePadding: 55,
  nodeFontColor: "black",
  nodeColor: {
    default: "#ff8500",
    inactive: "#808080"
  },
  linkColor: {
    default: "#ffc900",
    inactive: "#D3D3D3"
  },
  opacity: {
    nodeOpacityDefault: 1,
    nodeOpacityInactive: 0.1,
    LinkOpacityDefault: 1,
    LinkOpacityInactive: 0.1
  },
  storyNodeFontColor: "#006778",
  storyNodeText: [],
  nodeValueStyle: {
    textBefore: "(",
    textAfter: ")"
  },
  data: []
}, Ct = [], It = "332", mt = [
  {
    Date: "1/15/2016",
    "Data 1": "$1,000",
    "Data 2": "ABC",
    "Data 3": "100",
    "Data 4": "90",
    "Monthly-Goal": "100"
  },
  {
    Date: "2/15/2016",
    "Data 1": "100",
    "Data 2": "110",
    "Data 3": "100",
    "Data 4": "100",
    "Monthly-Goal": "100"
  },
  {
    Date: "3/15/2016",
    "Data 1": "80",
    "Data 2": "90",
    "Data 3": "100",
    "Data 4": "120",
    "Monthly-Goal": "110"
  },
  {
    Date: "4/15/2016",
    "Data 1": "80",
    "Data 2": "90",
    "Data 3": "110",
    "Data 4": "120",
    "Monthly-Goal": "110"
  },
  {
    Date: "5/15/2016",
    "Data 1": "70",
    "Data 2": "90",
    "Data 3": "110",
    "Data 4": "130",
    "Monthly-Goal": "120"
  },
  {
    Date: "6/15/2016",
    "Data 1": "100",
    "Data 2": "120",
    "Data 3": "120",
    "Data 4": "130",
    "Monthly-Goal": "120"
  },
  {
    Date: "7/15/2016",
    "Data 1": "110",
    "Data 2": "140",
    "Data 3": "120",
    "Data 4": "130",
    "Monthly-Goal": "130"
  },
  {
    Date: "8/15/2016",
    "Data 1": "110",
    "Data 2": "130",
    "Data 3": "120",
    "Data 4": "140",
    "Monthly-Goal": "130"
  },
  {
    Date: "9/15/2016",
    "Data 1": "120",
    "Data 2": "",
    "Data 3": "120",
    "Data 4": "150",
    "Monthly-Goal": "140"
  }
], Tt = "Bar", vt = [], Rt = 4.23, At = 0, Gt = "4.24.4", Vt = {
  type: C,
  debugSvg: I,
  chartMessage: m,
  title: T,
  showTitle: v,
  showDownloadMediaButton: R,
  theme: A,
  animate: G,
  fontSize: V,
  lineDatapointStyle: b,
  lineDatapointColor: F,
  barHasBorder: E,
  isLollipopChart: w,
  lollipopShape: O,
  lollipopColorStyle: H,
  visualizationSubType: P,
  barStyle: M,
  roundingStyle: x,
  tipRounding: Q,
  isResponsiveTicks: U,
  general: k,
  padding: Y,
  preliminaryData: z,
  yAxis: B,
  boxplot: $,
  topAxis: N,
  isLegendValue: W,
  barThickness: j,
  barHeight: K,
  barSpace: q,
  heights: X,
  xAxis: J,
  table: Z,
  orientation: tt,
  color: at,
  columns: et,
  legend: ot,
  brush: it,
  exclusions: rt,
  palette: nt,
  isPaletteReversed: ct,
  twoColor: lt,
  labels: st,
  dataFormat: dt,
  confidenceKeys: St,
  visual: gt,
  useLogScale: ft,
  filterBehavior: Lt,
  highlightedBarValues: _t,
  series: ut,
  tooltips: pt,
  forestPlot: yt,
  area: ht,
  sankey: Dt,
  suppressedData: Ct,
  height: It,
  data: mt,
  visualizationType: Tt,
  filters: vt,
  validated: Rt,
  dynamicMarginTop: At,
  version: Gt
}, bt = "chart", Ft = "Line", Et = {
  dataKey: "STATE"
}, wt = [
  {
    dataKey: "Rate"
  }
], Ot = [
  {
    values: [
      "Home",
      "School",
      "Vehicle",
      "Work"
    ],
    active: "Home",
    order: "asc",
    columnName: "Location",
    setByQueryParameter: "location"
  }
], Ht = [
  {
    STATE: "AL",
    Rate: "10",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  }
], Pt = "hex-data.csv", Mt = "file", xt = [
  {
    STATE: "AL",
    Rate: "10",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  }
], Qt = {
  horizontal: !1,
  series: !1
}, Ut = {
  type: bt,
  visualizationType: Ft,
  xAxis: Et,
  series: wt,
  filters: Ot,
  data: Ht,
  dataFileName: Pt,
  dataFileSourceType: Mt,
  formattedData: xt,
  dataDescription: Qt
}, kt = !0, Yt = "chart", zt = "Line", Bt = {
  dataKey: "STATE"
}, $t = [
  {
    dataKey: "Rate"
  }
], Nt = [
  {
    values: [
      "Home",
      "School",
      "Vehicle",
      "Work"
    ],
    active: "Home",
    order: "asc",
    columnName: "Location",
    setByQueryParameter: "location"
  }
], Wt = [
  {
    STATE: "AL",
    Rate: "10",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  }
], jt = "hex-data.csv", Kt = "file", qt = [
  {
    STATE: "AL",
    Rate: "10",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AK",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "10",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "12",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  }
], Xt = {
  horizontal: !1,
  series: !1
}, Jt = {
  allowLineToBarGraph: kt,
  type: Yt,
  visualizationType: zt,
  xAxis: Bt,
  series: $t,
  filters: Nt,
  data: Wt,
  dataFileName: jt,
  dataFileSourceType: Kt,
  formattedData: qt,
  dataDescription: Xt
}, Zt = "chart", ta = "Lollipop Style Horizontal Bar Chart - Number of Spills Occurring in the Home", aa = !0, ea = !1, oa = "theme-blue", ia = !0, ra = "medium", na = "hover", ca = "false", la = !0, sa = "circle", da = "two-tone", Sa = "horizontal", ga = "", fa = "standard", La = "top", _a = !1, ua = {
  showDownloadButton: !1
}, pa = {
  left: 5,
  right: 5
}, ya = {
  hideAxis: !0,
  displayNumbersOnBar: !0,
  hideLabel: !1,
  hideTicks: !1,
  size: "13",
  gridLines: !1,
  enablePadding: !1,
  min: "",
  max: "",
  labelColor: "#333",
  tickLabelColor: "#333",
  tickColor: "#333",
  rightHideAxis: !0,
  rightAxisSize: 50,
  rightLabel: "",
  rightLabelOffsetSize: 0,
  rightAxisLabelColor: "#333",
  rightAxisTickLabelColor: "#333",
  rightAxisTickColor: "#333",
  numTicks: "9",
  axisPadding: 0,
  tickRotation: 0,
  anchors: [],
  type: "chart",
  title: "Lollipop Style Horizontal Bar Chart",
  theme: "theme-blue",
  fontSize: "medium",
  lineDatapointStyle: "hover",
  barHasBorder: "false",
  isLollipopChart: !1,
  lollipopShape: "circle",
  lollipopColorStyle: "two-tone",
  visualizationSubType: "horizontal",
  padding: {
    left: 5,
    right: 5
  },
  yAxis: {
    size: 50,
    gridLines: !1
  },
  barThickness: 0.35,
  height: 260,
  xAxis: {
    type: "categorical",
    size: 75,
    tickRotation: 0,
    dataKey: "Vehicle"
  },
  table: {
    label: "Data Table",
    expanded: !0,
    show: !0
  },
  legend: {
    behavior: "isolate",
    position: "right"
  },
  exclusions: {
    active: !1,
    keys: []
  },
  palette: "qualitative-bold",
  labels: !1,
  dataFormat: {},
  confidenceKeys: {},
  data: [
    {
      Group: "Combined Total of Group A",
      Vehicle: "100",
      Home: "120",
      Work: "140",
      Office: "120"
    },
    {
      Group: "Combined Total of Group B",
      Vehicle: "150",
      Home: "140",
      Work: "100",
      Office: "90"
    },
    {
      Group: "Combined Total of Group C",
      Vehicle: "90",
      Home: "90",
      Work: "80",
      Office: "80"
    },
    {
      Group: "Combined Total of Group D",
      Vehicle: "70",
      Home: "60",
      Work: "50",
      Office: "70"
    }
  ],
  dataFileName: "CSV_Source_Example_for_Horizontal_Bar_viz-cdcwp1619811744363.csv",
  dataFileSourceType: "file",
  visualizationType: "Bar",
  runtime: {
    seriesLabels: {
      Vehicle: "Vehicle"
    },
    seriesLabelsAll: [
      "Vehicle"
    ],
    originalXAxis: {
      type: "categorical",
      size: 75,
      tickRotation: 0,
      dataKey: "Vehicle"
    },
    seriesKeys: [
      "Vehicle"
    ],
    xAxis: {
      size: 50,
      gridLines: !1
    },
    yAxis: {
      type: "categorical",
      size: 75,
      tickRotation: 0,
      dataKey: "Vehicle"
    },
    horizontal: !0,
    uniqueId: 1651765968212,
    editorErrorMessage: ""
  },
  description: "Subtext can be added here for options like citing data sources or insight into reading the bar chart.",
  series: [
    {
      dataKey: "Vehicle",
      type: "Bar"
    }
  ],
  barHeight: 25,
  barPadding: 40,
  labelPlacement: "Below Bar",
  label: "Number of Accidents"
}, ha = [], Da = {
  hasLine: !1
}, Ca = !1, Ia = 0.35, ma = 6, Ta = 15, va = {
  vertical: 300,
  horizontal: 170.39999999999998
}, Ra = {
  anchors: [],
  type: "categorical",
  showTargetLabel: !0,
  targetLabel: "Target",
  hideAxis: !0,
  hideLabel: !0,
  hideTicks: !0,
  size: "16",
  tickRotation: 0,
  min: "",
  max: "160",
  labelColor: "#333",
  tickLabelColor: "#333",
  tickColor: "#333",
  numTicks: "",
  labelOffset: 65,
  axisPadding: 0,
  target: 0,
  maxTickRotation: 0,
  dataKey: "Group"
}, Aa = {
  label: "Data Table",
  expanded: !1,
  limitHeight: !1,
  height: "",
  caption: "",
  showDownloadUrl: !1,
  showDataTableLink: !0,
  indexLabel: "Group",
  download: !1,
  showVertical: !0,
  show: !0
}, Ga = "horizontal", Va = "pinkpurple", ba = {}, Fa = {
  behavior: "isolate",
  singleRow: !1,
  colorCode: "",
  reverseLabelOrder: !1,
  description: "",
  dynamicLegend: !1,
  dynamicLegendDefaultText: "Show All",
  dynamicLegendItemLimit: 5,
  dynamicLegendItemLimitMessage: "Dynamic Legend Item Limit Hit.",
  dynamicLegendChartMessage: "Select Options from the Legend",
  position: "right",
  hide: !0,
  label: "Accident Location"
}, Ea = {
  active: !1,
  keys: []
}, wa = "qualitative-bold", Oa = !1, Ha = {
  palette: "monochrome-1",
  isPaletteReversed: !1
}, Pa = !1, Ma = {
  commas: !1,
  prefix: "",
  suffix: "",
  abbreviated: !1,
  bottomSuffix: "",
  bottomPrefix: "",
  bottomAbbreviated: !1
}, xa = {}, Qa = {
  border: !0,
  accent: !0,
  background: !0,
  verticalHoverLine: !1,
  horizontalHoverLine: !1
}, Ua = !1, ka = "Filter Change", Ya = [], za = [
  {
    dataKey: "Home",
    type: "Bar",
    tooltip: !0
  }
], Ba = {
  opacity: 90
}, $a = 212, Na = [
  {
    Group: "Combined Total of Group A",
    Vehicle: "100",
    Home: "120",
    Work: "140",
    Office: "120"
  },
  {
    Group: "Combined Total of Group B",
    Vehicle: "150",
    Home: "140",
    Work: "100",
    Office: "90"
  },
  {
    Group: "Combined Total of Group C",
    Vehicle: "90",
    Home: "90",
    Work: "80",
    Office: "80"
  },
  {
    Group: "Combined Total of Group D",
    Vehicle: "70",
    Home: "60",
    Work: "50",
    Office: "70"
  }
], Wa = "CSV_Source_Example_for_Horizontal_Bar_viz-cdcwp1619811744363.csv", ja = "file", Ka = "Bar", qa = "Subtext can be added here for options like citing data sources or insight into reading the bar chart.", Xa = 47, Ja = [], Za = "medium", te = 4.23, ae = 0, ee = {
  type: Zt,
  title: ta,
  showTitle: aa,
  showDownloadMediaButton: ea,
  theme: oa,
  animate: ia,
  fontSize: ra,
  lineDatapointStyle: na,
  barHasBorder: ca,
  isLollipopChart: la,
  lollipopShape: sa,
  lollipopColorStyle: da,
  visualizationSubType: Sa,
  barStyle: ga,
  roundingStyle: fa,
  tipRounding: La,
  isResponsiveTicks: _a,
  general: ua,
  padding: pa,
  yAxis: ya,
  boxplot: ha,
  topAxis: Da,
  isLegendValue: Ca,
  barThickness: Ia,
  barHeight: ma,
  barSpace: Ta,
  heights: va,
  xAxis: Ra,
  table: Aa,
  orientation: Ga,
  color: Va,
  columns: ba,
  legend: Fa,
  exclusions: Ea,
  palette: wa,
  isPaletteReversed: Oa,
  twoColor: Ha,
  labels: Pa,
  dataFormat: Ma,
  confidenceKeys: xa,
  visual: Qa,
  useLogScale: Ua,
  filterBehavior: ka,
  highlightedBarValues: Ya,
  series: za,
  tooltips: Ba,
  height: $a,
  data: Na,
  dataFileName: Wa,
  dataFileSourceType: ja,
  visualizationType: Ka,
  description: qa,
  barPadding: Xa,
  filters: Ja,
  lollipopSize: Za,
  validated: te,
  dynamicMarginTop: ae
}, oe = "chart", ie = "Line", re = {
  dataKey: "YearStart"
}, ne = [
  {
    dataKey: "Data_Value"
  }
], ce = [], le = [
  {
    ID: 144917,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 40.8,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 38.6,
    High_Confidence_Limit: 43,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group3",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 151361,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 36.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 33,
    High_Confidence_Limit: 39.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The United States includes 50 states plus the District of Columbia, unless otherwise noted.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 149260,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 56.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 54.1,
    High_Confidence_Limit: 58.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group2",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 153072,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 49.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 45.8,
    High_Confidence_Limit: 53,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The Northeast Region includes Connecticut, Maine, Massachusetts, New Jersey, New Hampshire, New York, Pennsylvania, Rhode Island and Vermont.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 23204,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 52.3,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 50.1,
    High_Confidence_Limit: 54.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 23204,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 52.3,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 50.1,
    High_Confidence_Limit: 54.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 153493,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 47.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 45.8,
    High_Confidence_Limit: 49,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 150047,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 37.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 34.2,
    High_Confidence_Limit: 40.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The South Region includes Alabama, Arkansas, Delaware, District of Columbia, Florida, Georgia, Kentucky, Louisiana, Maryland, Mississippi, North Carolina, Oklahoma, South Carolina, Tennessee, Texas, Virginia, and West Virginia.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 153477,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.4,
    High_Confidence_Limit: 43.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 146615,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 50.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47.4,
    High_Confidence_Limit: 53.7,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The West Region includes Alaska, Arizona, California, Colorado, Hawaii, Idaho, Montana, New Mexico, Nevada, Oregon, Utah, Washington, and Wyoming.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 151896,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 57.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 55.2,
    High_Confidence_Limit: 59.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 148911,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 48.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47,
    High_Confidence_Limit: 50,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 24803,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 38.8,
    High_Confidence_Limit: 43.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy Brain Initiative",
    URL: "http://wwwdev.cdc.gov/aging/healthybrain/index.htm",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 24803,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 38.8,
    High_Confidence_Limit: 43.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy Brain Initiative",
    URL: "http://wwwdev.cdc.gov/aging/healthybrain/index.htm",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 148620,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 37.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 34.1,
    High_Confidence_Limit: 41.1,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Data Source: Behavior Risk Factor Surveillance System (BRFSS) http://www.cdc.gov/brfss/.  All responses are self-reported by adults 18 years or older.",
    URL: "http://www.cdc.gov/brfss/index.html",
    FootnoteHeading: "Data Source",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 153143,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 42.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.9,
    High_Confidence_Limit: 44.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 147461,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 50.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 46.9,
    High_Confidence_Limit: 53.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Centers for Disease Control and Prevention. National Center for Chronic Disease Prevention and Health Promotion, Division of Population Health. Healthy Aging Data [online].",
    URL: "https://www.cdc.gov/aging/agingdata/index.html",
    FootnoteHeading: "Suggested Citation",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 154789,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 56.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 54.1,
    High_Confidence_Limit: 58.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 149618,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 48.6,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47.1,
    High_Confidence_Limit: 50.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 82879,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 54.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 52.2,
    High_Confidence_Limit: 57.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 82879,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 54.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 52.2,
    High_Confidence_Limit: 57.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 66185,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 35.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 31.7,
    High_Confidence_Limit: 39.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Using the Healthy Aging Data",
    URL: "http://wwwdev.cdc.gov/aging/agingdata/data-portal/index.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 76480,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.9,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.1,
    High_Confidence_Limit: 44.7,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 75307,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 51.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47.2,
    High_Confidence_Limit: 55.1,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Calls to Action",
    URL: "http://wwwdev.cdc.gov/aging/agingdata/data-portal/callstoaction.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 86482,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 56.9,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 54.4,
    High_Confidence_Limit: 59.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 80122,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 49,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47.1,
    High_Confidence_Limit: 50.8,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 87429,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 42.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.7,
    High_Confidence_Limit: 45.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy Aging Program",
    URL: "http://wwwdev.cdc.gov/aging/index.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 87429,
    YearStart: 2020,
    YearEnd: 2020,
    Description: 2020,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 42.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.7,
    High_Confidence_Limit: 45.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy Aging Program",
    URL: "http://wwwdev.cdc.gov/aging/index.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 26817,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 34.6,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 31.4,
    High_Confidence_Limit: 37.9,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy People 2020: Older Adults",
    URL: "http://wwwdev.cdc.gov/aging/agingdata/data-portal/healthy-people.html#HealthyPeopleObjectives",
    FootnoteHeading: "Related Links",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 27140,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 40.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 38.1,
    High_Confidence_Limit: 42.7,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 22363,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 54.2,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 52,
    High_Confidence_Limit: 56.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 31857,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 48.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 45.4,
    High_Confidence_Limit: 52,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "State and Community Examples",
    URL: "http://wwwdev.cdc.gov/aging/agingdata/data-portal/state-community.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 23073,
    YearStart: 2021,
    YearEnd: 2021,
    Description: 2021,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 47.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 45.5,
    High_Confidence_Limit: 48.7,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 147123,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 52.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 50.6,
    High_Confidence_Limit: 54.8,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 147123,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 52.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 50.6,
    High_Confidence_Limit: 54.8,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 256563,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 39.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 36.8,
    High_Confidence_Limit: 41.3,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "50-64 yearsOverall"
  },
  {
    ID: 286317,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 33.6,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 30.5,
    High_Confidence_Limit: 36.8,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "50-64 years",
    StratificationId1: 5064,
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Healthy People 2030: Dementia",
    URL: "https://health.gov/healthypeople/objectives-and-data/browse-objectives/dementias",
    FootnoteHeading: "Related Links",
    SeriesDesc: "50-64 yearsGender"
  },
  {
    ID: 264047,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 50.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 47.2,
    High_Confidence_Limit: 53,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Additional Resources",
    URL: "http://wwwdev.cdc.gov/aging/agingdata/data-portal/related-links.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "65 years or olderGender"
  },
  {
    ID: 275104,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 56.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 54.6,
    High_Confidence_Limit: 58.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "65 years or older",
    StratificationId1: "65PLUS",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "65 years or olderOverall"
  },
  {
    ID: 271486,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 47.7,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 46.2,
    High_Confidence_Limit: 49.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Overall",
    StratificationCategoryId2: "OVERALL",
    Stratification2: "Overall",
    StratificationId2: "OVERALL",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallOverall"
  },
  {
    ID: 149713,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.4,
    High_Confidence_Limit: 55.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 149713,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.4,
    High_Confidence_Limit: 55.5,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 149770,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39,
    High_Confidence_Limit: 43.9,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Data Source: Behavioral Risk Factor Surveillance System (BRFSS)",
    URL: "http://www.cdc.gov/brfss/",
    FootnoteHeading: "Data Source",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 149770,
    YearStart: 2015,
    YearEnd: 2015,
    Description: 2015,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39,
    High_Confidence_Limit: 43.9,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Data Source: Behavioral Risk Factor Surveillance System (BRFSS)",
    URL: "http://www.cdc.gov/brfss/",
    FootnoteHeading: "Data Source",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 153627,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.5,
    High_Confidence_Limit: 55.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 153627,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.5,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.5,
    High_Confidence_Limit: 55.4,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 154889,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 43.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 40.7,
    High_Confidence_Limit: 45.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "CI = Confidence Interval.  CI describes the level of uncertainty of an estimate and specifies the range in which the true value is likely to fall. These reports use a 95% level of significance, which means that 95% of the time, the true value falls within these boundaries. When comparing prevalence of variables across states or years, we recommend the use of confidence intervals. If the confidence intervals overlap, the difference is not statistically significant.",
    URL: "",
    FootnoteHeading: "Measure Definitions",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 154889,
    YearStart: 2019,
    YearEnd: 2019,
    Description: 2019,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 43.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 40.7,
    High_Confidence_Limit: 45.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "CI = Confidence Interval.  CI describes the level of uncertainty of an estimate and specifies the range in which the true value is likely to fall. These reports use a 95% level of significance, which means that 95% of the time, the true value falls within these boundaries. When comparing prevalence of variables across states or years, we recommend the use of confidence intervals. If the confidence intervals overlap, the difference is not statistically significant.",
    URL: "",
    FootnoteHeading: "Measure Definitions",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 155508,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 42.9,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 40.6,
    High_Confidence_Limit: 45.1,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The Midwest Region includes Ohio, Indiana, Michigan, Illinois, Wisconsin, Iowa, Kansas, Missouri, Minnesota, Nebraska, South Dakota, and North Dakota.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 155508,
    YearStart: 2017,
    YearEnd: 2017,
    Description: 2017,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 42.9,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 40.6,
    High_Confidence_Limit: 45.1,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "The Midwest Region includes Ohio, Indiana, Michigan, Illinois, Wisconsin, Iowa, Kansas, Missouri, Minnesota, Nebraska, South Dakota, and North Dakota.",
    URL: "",
    FootnoteHeading: "Notes",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 275106,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.3,
    High_Confidence_Limit: 43.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Male",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Division of Population Health",
    URL: "http://wwwdev.cdc.gov/nccdphp/dph/index.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 275106,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 41.4,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 39.3,
    High_Confidence_Limit: 43.6,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "MALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "Division of Population Health",
    URL: "http://wwwdev.cdc.gov/nccdphp/dph/index.html",
    FootnoteHeading: "Related Links",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 278854,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.1,
    High_Confidence_Limit: 55.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "Female",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  },
  {
    ID: 278854,
    YearStart: 2022,
    YearEnd: 2022,
    Description: 2022,
    LocationAbbr: "MI",
    LocationDesc: "Michigan",
    DataSource: "BRFSS",
    Class: "Overall Health",
    Topic: "Arthritis among older adults",
    Question: "Percentage of older adults ever told they have arthritis",
    Response: "",
    Data_Value_Unit: "%",
    DataValueTypeId: "PRCTG",
    Data_Value_Type: "Percentage",
    Data_Value: 53.1,
    Data_Value_Footnote_Symbol: "",
    Data_Value_Footnote: "",
    Low_Confidence_Limit: 51.1,
    High_Confidence_Limit: 55.2,
    Sample_Size: "",
    GeoLocation_Lat: "",
    GeoLocation_Long: "",
    ClassId: "C01",
    TopicId: "TOC11",
    QuestionId: "Q43",
    ResponseId: "",
    StratificationCategory1: "Age Group2",
    StratificationCategoryId1: "AGE",
    Stratification1: "Overall",
    StratificationId1: "AGE_OVERALL",
    StratificationCategory2: "Gender",
    StratificationCategoryId2: "GENDER",
    Stratification2: "All",
    StratificationId2: "FEMALE",
    StratificationCategory3: "",
    StratificationCategoryId3: "",
    Stratification3: "",
    StratificationId3: "",
    FootnoteSymbol: "",
    FootnoteText: "",
    URL: "",
    FootnoteHeading: "",
    SeriesDesc: "OverallGender"
  }
], se = "hex-data.csv", de = "file", Se = [
  {
    STATE: "AL",
    Rate: "10",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "30",
    Location: "Vacation",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Increasing"
  },
  {
    STATE: "AL",
    Rate: "20",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Decreasing"
  },
  {
    STATE: "AL",
    Rate: "15",
    Location: "Vehicle",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Decreasing"
  },
  {
    STATE: "AL",
    Rate: "25",
    Location: "School",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Decreasing"
  },
  {
    STATE: "AL",
    Rate: "28",
    Location: "Vehicle",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Decreasing"
  },
  {
    STATE: "FL",
    Rate: "12",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "43",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "FL",
    Rate: "65",
    Location: "Vehicle",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Decreasing"
  },
  {
    STATE: "GA",
    Rate: "32",
    Location: "Home",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "92",
    Location: "Work",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "102",
    Location: "Vehicle",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "Low",
    Trajectory: "Increasing"
  },
  {
    STATE: "GA",
    Rate: "102",
    Location: "N/A",
    URL: "https://www.cdc.gov/",
    "Intensity Level": "High",
    Trajectory: "Increasing"
  }
], ge = {
  horizontal: !1,
  series: !1
}, fe = {
  type: oe,
  visualizationType: ie,
  xAxis: re,
  series: ne,
  filters: ce,
  data: le,
  dataFileName: se,
  dataFileSourceType: de,
  formattedData: Se,
  dataDescription: ge
}, eo = {
  title: "Components/Templates/Chart",
  component: D
}, t = {
  args: {
    config: Ut,
    isEditor: !1
  }
}, a = {
  args: {
    config: Jt,
    isEditor: !1
  }
}, e = {
  args: {
    config: fe,
    isEditor: !0
  }
}, o = {
  args: {
    config: ee,
    isEditor: !1
  }
}, i = {
  args: {
    config: Vt,
    isEditor: !1
  }
};
var r, n, c;
t.parameters = {
  ...t.parameters,
  docs: {
    ...(r = t.parameters) == null ? void 0 : r.docs,
    source: {
      originalSource: `{
  args: {
    config: lineChartTwoPointsRegressionTest,
    isEditor: false
  }
}`,
      ...(c = (n = t.parameters) == null ? void 0 : n.docs) == null ? void 0 : c.source
    }
  }
};
var l, s, d;
a.parameters = {
  ...a.parameters,
  docs: {
    ...(l = a.parameters) == null ? void 0 : l.docs,
    source: {
      originalSource: `{
  args: {
    config: lineChartTwoPointsNewChart,
    isEditor: false
  }
}`,
      ...(d = (s = a.parameters) == null ? void 0 : s.docs) == null ? void 0 : d.source
    }
  }
};
var S, g, f;
e.parameters = {
  ...e.parameters,
  docs: {
    ...(S = e.parameters) == null ? void 0 : S.docs,
    source: {
      originalSource: `{
  args: {
    config: nestedDropdownSample,
    isEditor: true
  }
}`,
      ...(f = (g = e.parameters) == null ? void 0 : g.docs) == null ? void 0 : f.source
    }
  }
};
var L, _, u;
o.parameters = {
  ...o.parameters,
  docs: {
    ...(L = o.parameters) == null ? void 0 : L.docs,
    source: {
      originalSource: `{
  args: {
    config: lollipop,
    isEditor: false
  }
}`,
      ...(u = (_ = o.parameters) == null ? void 0 : _.docs) == null ? void 0 : u.source
    }
  }
};
var p, y, h;
i.parameters = {
  ...i.parameters,
  docs: {
    ...(p = i.parameters) == null ? void 0 : p.docs,
    source: {
      originalSource: `{
  args: {
    config: SuppressedConfig,
    isEditor: false
  }
}`,
      ...(h = (y = i.parameters) == null ? void 0 : y.docs) == null ? void 0 : h.source
    }
  }
};
const oo = ["line_Chart_Two_Points_Regression_Test", "line_Chart_Two_Points_New_Chart", "nested_dropdown_sample", "Lollipop", "Suppression"];
export {
  o as Lollipop,
  i as Suppression,
  oo as __namedExportsOrder,
  eo as default,
  a as line_Chart_Two_Points_New_Chart,
  t as line_Chart_Two_Points_Regression_Test,
  e as nested_dropdown_sample
};
