import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import CdcMap from '../CdcMap'
import { assertVisualizationRendered, waitForPresence, waitForEditor, openAccordion } from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof CdcMap> = {
  title: 'Components/Templates/Map/Accessible Alt Text',
  component: CdcMap,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates SVG accessibility for maps: auto-generated aria-label with optional configurable description concatenated into the label for reliable screen reader support.'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof CdcMap>

export const MetadataDescription: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Description pulled from dataMetadata is concatenated into the aria-label after the auto-generated title for reliable screen reader support.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    const expected = `United States map with the title: COVID-19 Case Rates by State. ${altTextConfig.dataMetadata.altDescription}`
    expect(svg?.getAttribute('aria-label')).toBe(expected)
  }
}

export const StaticDescription: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        type: 'static',
        value: 'US map showing COVID-19 rates concentrated in the Southeast region.'
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story: 'Static manually written description concatenated with the auto-generated title.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    expect(svg?.getAttribute('aria-label')).toBe(
      'United States map with the title: COVID-19 Case Rates by State. US map showing COVID-19 rates concentrated in the Southeast region.'
    )
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured. Falls back to the auto-generated aria-label: "United States map with the title: COVID-19 Case Rates by State".'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)
    const svg = await waitForPresence('svg[role="img"]', canvasElement)

    expect(svg?.getAttribute('aria-label')).toBe('United States map with the title: COVID-19 Case Rates by State')
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story:
          'Editor mode showing the alt text description control in the General accordion with metadata-driven description.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    await openAccordion(canvas, 'General')

    const descPreview = await waitForPresence('[data-testid="alt-text-desc-preview"]', canvasElement)
    expect(descPreview?.textContent).toContain('Choropleth map of the United States')
  }
}
