/**
  * This file is auto-generated by "generateRespiratoryStories.js".
  * DO NOT EDIT THIS FILE DIRECTLY.
  */

import CdcMap from '../CdcMap'
import ARI_Map_Viz_config from './_mock/respiratory-virus/ARI_Map_Viz.json';
import CFA_Map_Viz_config from './_mock/respiratory-virus/CFA_Map_Viz.json';
import wastewatermap_config from './_mock/respiratory-virus/wastewatermap.json';

const meta = {
  title: 'Components/Templates/Map/Respiratory Virus',
  component: CdcMap
}

export default meta


  export const ARI_Map_Viz = {
    args: { config: ARI_Map_Viz_config }
  };

  export const CFA_Map_Viz = {
    args: { config: CFA_Map_Viz_config }
  };

  export const wastewatermap = {
    args: { config: wastewatermap_config }
  };
