import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import CdcMap from '../CdcMap'
import { assertVisualizationRendered, waitForEditor, openAccordion } from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof CdcMap> = {
  title: 'Components/Templates/Map/Accessible Alt Text',
  component: CdcMap,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates SVG title/desc accessibility for maps: auto-generated, static override, and metadata-driven modes for both title and description.'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof CdcMap>

const expectedMetadataDesc = altTextConfig.dataMetadata.altDescription

export const MetadataDriven: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'metadata', metadataKey: 'altTitle' },
        description: { type: 'metadata', metadataKey: 'altDescription' }
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Both title and description pulled from dataMetadata. The SVG contains <title> and <desc> elements referenced via aria-labelledby.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe(altTextConfig.dataMetadata.altTitle)

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe(expectedMetadataDesc)

    expect(svg?.getAttribute('aria-labelledby')).toContain(titleEl?.id)
    expect(svg?.getAttribute('aria-labelledby')).toContain(descEl?.id)
  }
}

export const StaticOverride: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'static', value: 'US COVID case rate map' },
        description: {
          type: 'static',
          value: 'US map showing COVID-19 rates concentrated in the Southeast region.'
        }
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story: 'Both title and description are static manually written strings.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('US COVID case rate map')

    const descEl = svg?.querySelector('desc')
    expect(descEl?.textContent).toBe('US map showing COVID-19 rates concentrated in the Southeast region.')
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured. Falls back to the auto-generated SVG title: "United States map with the title: COVID-19 Case Rates by State". No desc element is rendered.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()

    const titleEl = svg?.querySelector('title')
    expect(titleEl?.textContent).toBe('United States map with the title: COVID-19 Case Rates by State')

    const descEl = svg?.querySelector('desc')
    expect(descEl).toBeFalsy()
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        title: { type: 'metadata', metadataKey: 'altTitle' },
        description: { type: 'metadata', metadataKey: 'altDescription' }
      }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story:
          'Editor mode showing the alt text controls in the General accordion with both title and description from metadata.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    await openAccordion(canvas, 'General')

    const previewText = canvasElement.querySelector('[data-testid="alt-text-preview"]')
    expect(previewText).toBeTruthy()
    expect(previewText?.textContent).toContain('US COVID-19 case rate map')

    const descPreview = canvasElement.querySelector('[data-testid="alt-text-desc-preview"]')
    expect(descPreview).toBeTruthy()
    expect(descPreview?.textContent).toContain('Choropleth map of the United States')
  }
}
