import type { Meta, StoryObj } from '@storybook/react-vite'
import { within, expect } from 'storybook/test'
import CdcMap from '../CdcMap'
import { assertVisualizationRendered, waitForEditor, openAccordion } from '@cdc/core/helpers/testing'
import altTextConfig from './_mock/alt_text_metadata.json'

const meta: Meta<typeof CdcMap> = {
  title: 'Components/Templates/Map/Accessible Alt Text',
  component: CdcMap,
  parameters: {
    docs: {
      description: {
        component:
          'Demonstrates the three alt text modes for maps: auto-generated (default), static (manual override), and metadata-driven (pulled from data file metadata).'
      }
    }
  }
}

export default meta
type Story = StoryObj<typeof CdcMap>

const expectedMetadataAlt = altTextConfig.dataMetadata.altDescription

export const MetadataDriven: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'Alt text type set to "metadata" with key "altDescription". The SVG aria-label is populated from dataMetadata.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe(expectedMetadataAlt)
  }
}

export const StaticOverride: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: {
        type: 'static',
        value: 'US map showing COVID-19 rates concentrated in the Southeast region.'
      }
    },
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story: 'Alt text type set to "static" with a manually written description.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe('US map showing COVID-19 rates concentrated in the Southeast region.')
  }
}

export const AutoGenerated: Story = {
  args: {
    config: altTextConfig,
    isEditor: false
  },
  parameters: {
    docs: {
      description: {
        story:
          'No altText configured. Falls back to the auto-generated aria-label: "United States map with the title: COVID-19 Case Rates by State".'
      }
    }
  },
  play: async ({ canvasElement }) => {
    await assertVisualizationRendered(canvasElement)

    const svg = canvasElement.querySelector('svg[role="img"]')
    expect(svg).toBeTruthy()
    expect(svg?.getAttribute('aria-label')).toBe('United States map with the title: COVID-19 Case Rates by State')
  }
}

export const EditorWithMetadata: Story = {
  args: {
    config: {
      ...altTextConfig,
      altText: { type: 'metadata', metadataKey: 'altDescription' }
    },
    isEditor: true
  },
  parameters: {
    docs: {
      description: {
        story: 'Editor mode showing the alt text controls in the General accordion with metadata selected.'
      }
    }
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await waitForEditor(canvas)

    await openAccordion(canvas, 'General')

    const previewText = canvasElement.querySelector('[data-testid="alt-text-preview"]')
    expect(previewText).toBeTruthy()
    expect(previewText?.textContent).toContain('Choropleth map of the United States')
  }
}
