const fs = require('fs')
const path = require('path')

// Paths
const CONFIG_DIR = path.join(__dirname, '_mock', 'respiratory-virus')
const STORIES_DIR = path.join(__dirname, 'CdcMap.RespiratoryVirus.stories.js')

// Grab all .json files
const configFiles = fs.readdirSync(CONFIG_DIR).filter(file => file.endsWith('.json'))

const imports = [`import CdcMap from '../CdcMap'`]
const storiesToExport = []

configFiles.forEach(filename => {
  const baseName = path.basename(filename, '.json')
  const importName = toValidIdentifier(baseName) + '_config'

  // Build up an import line, e.g.: import mapViz from './_mock/respiratory-virus/mapViz.json'
  imports.push(`import ${importName} from './_mock/respiratory-virus/${filename}';`)

  // Build up a named export, e.g.:
  // export const mapViz = {
  // args: { config: mapViz }
  // };
  storiesToExport.push(`
  export const ${baseName} = {
    args: { config: ${importName} }
  };`)
})

function toValidIdentifier(name) {
  return name.replace(/[^a-zA-Z0-9_$]/g, '_')
}

// Final file content:
const fileContent = `/**
  * This file is auto-generated by "generateRespiratoryStories.js".
  * DO NOT EDIT THIS FILE DIRECTLY.
  */

${imports.join('\n')}

const meta = {
  title: 'Components/Templates/Map/Respiratory Virus',
  component: CdcMap
}

export default meta

${storiesToExport.join('\n')}
`

fs.writeFileSync(STORIES_DIR, fileContent, 'utf-8')
console.log(`✅ Successfully generated CdcMap.RespiratoryVirus.stories.js`)
