name: Reject PRs with new .scss Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-scss-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Check for new .scss files in the PR
        run: |
          # Get the list of changed files in the PR
          added_files=$(git diff --diff-filter=A --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})

          # Check if any .scss files are present
          if echo "$added_files" | grep -q '\.scss$'; then
            echo "Error: PR contains newly added .scss files."
            exit 1
          else
            echo "No new .scss files found in the PR."
          fi
