name: Reject PRs with new .scss Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-scss-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for new .scss files in the PR
        run: |
          added_files=$(git diff --diff-filter=A --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }})

          if echo "$added_files" | grep -q '\.scss$'; then
            echo "Error: PR contains newly added .scss files."
            exit 1
          else
            echo "No new .scss files found in the PR."
          fi
