name: Storybook Deploy

on:
  push:
    branches: ['test']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: --max-old-space-size=6144

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn predeploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.storybook_build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
