name: Stylelint CSS

on:
  pull_request:
    paths:
      - 'packages/**/*.css'

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run stylelint on CSS files
        run: yarn lint:css
