name: Test Storybook

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  storybook-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Packages
        run: yarn build

      - name: Install Playwright with dependencies
        run: npx playwright install chromium --with-deps

      - name: Run Storybook tests
        run: yarn test-storybook
